### ISSUE TITLE
你好，感觉部分中文汉化不是很合理，能否参考一下静海流沙的汉化

### ISSUE THREAD

**Issue by easyinplay** [BoyceLig/ClashR.For.Windows#1]
你好，感谢你的打包工作，可以很方便找到更新的地方了，但感觉部分汉化有点像机翻也不太贴切，提供一些静海流沙的汉化，望采纳

**Comment by easyinplay** [comment]
附一下地址：https://www.lanzous.com/i9yhlpg，貌似只出过这一个版本就没再更新过了

**Comment by BoyceLig** [comment]
好的，我会改

**Comment by easyinplay** [comment]
非常感谢

**Comment by BoyceLig** [comment]
如果有不合理的可以具体的指出来，我刚刚看了下  好多都是我所理解的功能翻译，并不是机翻，你推荐我那个他的更像机翻，实际功能和翻译过来后不一致

**Comment by easyinplay** [comment]
proxy 感觉译为“代理”比较好，profile 目前看译为“订阅”，但像我既用机场也用自建的配置文件，翻译为本来的“配置”还是不错的，“连接信息”翻译的是原意，但取“连接”既能满足语意的需要也能上下对齐满足观感上的需要；翻译讲究“信雅达”，首先就是忠实原文，其次才是雅和达，你的翻译确实能让只使用第三方订阅的人明白自己要找东西的位置，但是译文已经加上了自身的理解和原文不太一样了。

**Comment by BoyceLig** [comment]
好，下个版本按照你的意见出
